{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Pages/ServiceOrders/ServiceItems/ServiceItemDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/ServiceOrders/ServiceItems/ServiceItemDetailsPageMetadata.js"
}