{
    "PopoverItems":
    [{
        "Title": "$(L,save)",
        "OnPress": "/SAPAssetManager/Rules/Documents/DocumentEditorSaveImageSave.js",
        "Visible" : true
    },
    {
        "Title": "$(L,save_as)",
        "OnPress": "/SAPAssetManager/Rules/Documents/DocumentEditorSaveImageSaveAs.js",
        "Visible" : true
    }],
    "_Type": "Action.Type.PopoverMenu"
}
