{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Details/NotificationDetailsPageMetadata.js"
}