{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/FunctionalLocation/FunctionalLocationDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/FunctionalLocation/FunctionalLocationDetailsPageMetadata.js"
}
