{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/ServiceOrders/ServiceOrderDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/ServiceOrders/ServiceOrderDetailsPageMetadata.js"
}